### ISSUE TITLE
How to use the streamer/dj account?

### ISSUE THREAD

**Issue by reans** [SlvrEagle23/AzuraCast#112]
hello. anyone knows how to use the streamer/dj account to stream directly in shoutcast? i try the user and password created in streamer account using Sam Broadcaster but no work.

**Comment by athensguy** [comment]
I tried it with icecast server and used RadioBoss built in wizard & it worked like charm. What is type of server you're using on AzuraCast end and what is your config on Sam caster?

**Comment by reans** [comment]
I used shoutcast v2. and i used the pormat dj user and dj password but no work.

**Comment by SlvrEagle23** [comment]
Hello all; just a quick update, I am aware of issues with streaming (especially to Shoutcast 2) and I'm working on an update that will resolve these issues and provide clearer instructions on the Streamers/DJs panel.

**Comment by SlvrEagle23** [comment]
Since the instructions for setting up streaming vary by each individual streaming software, and I don't have access to all pieces of popular streaming software myself, I've set up a wiki page where the community can contribute instructions on how to set up their favorite software. I got things started using the free and open-source software "BUTT" (Broadcast Using This Tool), which is easy to set up for AzuraCast.

https://github.com/SlvrEagle23/AzuraCast/wiki/Streaming-Software

If you would like to include instructions for your chosen piece of software (i.e. SAM broadcaster) it would be very welcome and appreciated. Once the Wiki page has been fleshed out more completely I plan to include a link to it directly from the AzuraCast Streamers/DJ page sidebar.

**Comment by reans** [comment]
Thank you for your support. I already update my installed azuracast. I saw the ICECAST and Shoutcast Client in DJ/Streamer page using Shoutcast 2 stream server with this port for ICECAST client : 8005 and the for Shoutcast v1 : 8006. I pretty sure the same procedure using the Centova Cast the shoutcast v1 djuser:djpassword format. But one problem ive try now in azuracast is this, i try to use the port given for shoutcast v1 which is 8006 with password format as mention djuser:password i wasnt connected but I try the port of icecast 8005 using the shoutcast server type option instead of icecast i was connect and the sound is double. the sound of live stream and the sound of autodj. The autodj must be stop if the live stream got IN but it wasnt stop. I try using the icecast type with the icecast port provide yes im still IN but same problem the sound is double from live source and the autodj source. thats what i notice.  any idea where is the problem?
