### ISSUE TITLE
request: record dj input

### ISSUE THREAD

**Issue by jeroenbauwen** [SlvrEagle23/AzuraCast#66]
Hi all,

I am trying to record the input when my dj's stream with the following liquidsoap code:

`output.file(%mp3, append = true, "/var/recorded/newshow.mp3", mksafe(input.http("http://localhost:8000/radio.mp3")))`

adding this code to the custom configuration on the profile page works, but, it will record the playlists aswell as the radio.mp3 mount will fall back to the autodj.mp3 mount.

To only record the live input, the code should be executed when the source connects to the server therefore it would be nice to have the `<on-connect>` mount-parameters in icecast.xml available.
Is it possible to add a `<on-connect>` and `<on-disconnect>` option to the advanced settings so we can execute scripts when sources connect or disconnect .

Thanks,
Jeroen

**Comment by SlvrEagle23** [comment]
@jeroenbauwen This is an excellent idea, and I definitely appreciate your thoroughness in describing the issue in detail!

I have pushed up a new change that allows you to specify any custom configuration you want added to the frontend (IceCast). You can specify it either as `<on-connect>test</on-connect>` or `{"on-connect": "test"}` and the code will add it to the mount's configuration. Since this is the last step in mount config, you can also use this to override mount defaults specified by the code itself higher up.
