### ISSUE TITLE
External shoutcast v2 server with multiple sids

### ISSUE THREAD

**Issue by kbysfm** [SlvrEagle23/AzuraCast#83]
For some reason I'm unable to pull stats from an external shoutcast stream if I append the SID at the end of the url. For example,

> http://serverip:port/index.html?sid=1 - AzuraCast doesn't pull stats for sid1. For some reason if I use http://serverip:port (without sid=1) it starts to work.

I want to be able to monitor the other streams on the same server so i figured the appropriate URL would be for the other two external stations

> http://serverip:port/index.html?sid=2 
> http://serverip:port/index.html?sid=3

Any help would be great!

Thanks again.

**Comment by SlvrEagle23** [comment]
@kbysfm Sorry for the delay in getting back to you.

This is definitely a valid issue, and is likely caused by the fact that we append ?sid=1 to any URL that doesn't have it already, so that we can get valid XML data behind the scenes.

I'll push an update to the code as soon as I get a chance. I've been busy with full-time work lately, and that's led to me having less time to devote to AzuraCast. :(

**Comment by kbysfm** [comment]
@SlvrEagle23 I decided to start from scratch and try the docker version of AzuraCast. For some reason when adding an external shoutcast v2 server I noticed that /index.html?sid=2 and /index.html?sid=3 do not play music or show stats. The base url http://serverip:port works fine as advertised.

Thanks for hard work!
