### ISSUE TITLE
Add editable icecast config

### ISSUE THREAD

**Issue by 24dubstep** [SlvrEagle23/AzuraCast#84]
Hi, Please add the ability to edit the configuration the server icecast or the ability to add stations to the public directories

**Comment by mkody** [comment]
You can already do that for Icecast ("frontend") in your station's profile.
In the `Configure Radio Broadcasting`, there's a `Custom Configuration` input.

But adding a simple switch to add the station to the public directory could be a thing. @SlvrEagle23

**Comment by 24dubstep** [comment]
how to add ssl and public directories ??

**Comment by mkody** [comment]
You should visit Cloudflare's website on how to use TLS: https://www.cloudflare.com/ssl/

---

For Icecast, please read [Icecast docs](http://icecast.org/docs/icecast-2.4.0/config-file.html).
You must set the `public` variable for mountpoint to `1`. For this, you can use the  `Advanced Frontend Configuration` in your default mountpoint.

_Note: I can't test this since my installation is behind a firewall and that the directory can't access it directly._

![1484597577](https://cloud.githubusercontent.com/assets/843787/21997665/c3c52e30-dc30-11e6-8553-1d6aa34e782e.png)
![1484597609](https://cloud.githubusercontent.com/assets/843787/21997668/c5517fe2-dc30-11e6-9f11-0078f3f3ee20.png)
![1484597619](https://cloud.githubusercontent.com/assets/843787/21997671/c7518f26-dc30-11e6-9d2a-0e128fa5d0e7.png)
```json
{"public": "1"}
```
