### ISSUE TITLE
Install failed on Ubuntu server 16.04.1

### ISSUE THREAD

**Issue by colmrs** [SlvrEagle23/AzuraCast#95]
Hi there,
Is this a result of me using 16.04.1?

TASK [azuracast-db : Install Initial Database] *********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unable to find /home/engineering/.my.cnf. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: NO)\")"}

It was the only thing to fail

If not let me know if I can help at all?

Cheers 

Colm

**Comment by SlvrEagle23** [comment]
@colmrs Based on the error message, it looks like you're not running the initial installer as the actual root user. Unfortunately, due to a quirk in how Ubuntu 16.04 handles the MySQL root account, you have to actually be running _as_ the root user (not just a sudo-capable user) to do the initial installation. Any updates from then on can be done as a sudo-capable user.

**Comment by colmrs** [comment]
Yep I have just came to the same conclusion, just creating a new VM to try that on, as trying to then run the retry as root fails. Will close the issue if all is well. (Also sorry for not following the instructions) (would it be a good idea to add the "sudo passwd root" and "su" commands to the install so people dont make my same mistake?)

Thanks!

**Comment by colmrs** [comment]
User error, sorry about that!
